version: 2

orbs:
  node: circleci/node@4.0.0

jobs:
  build:
    docker:
    - image: circleci/node:12.21.0
    working_directory: ~/workspace
    steps:
      - checkout
      - run: yarn
      - run: yarn build
      - persist_to_workspace:
          root: /home/circleci/workspace
          paths:
          - .
  deploy:
    machine:
      image: circleci/classic:latest
    steps:
      - attach_workspace:
          at: ~/workspace
      - add_ssh_keys:
          fingerprints:
          - "fa:2e:bd:ba:d0:b9:63:84:eb:35:97:8d:ec:8e:70:cf"
      - run: echo ${CIRCLE_BRANCH}
      - run:
          name: "Deploy over SSH"
          command: | 
            export USER_HOST="root@104.131.11.225"
            tar -czf /tmp/dist.tar.gz -C ~/workspace/dist .
            ssh ${USER_HOST} '
            rm -Rf ~/apps/api/scheduling/workspace;
            mkdir ~/apps/api/scheduling/workspace;'

            scp -r /tmp/dist.tar.gz ${USER_HOST}:~/apps/api/scheduling/workspace/dist.tar.gz
            ssh ${USER_HOST} '
            cd ~/apps/api/scheduling/workspace;
            tar -xzf ./dist.tar.gz;
            rm -Rf ./dist.tar.gz;'
            
workflows:
  version: 2
  ci-dploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
     

