version: 2


jobs:
  build:
    docker:
    - image: circleci/node:12.21.0
    working_directory: ~/workspace
    steps:
      - checkout
      - run: yarn 
      - run: yarn build
      - persist_to_workspace:
          root: /home/circleci/workspace
          paths:
          - .
  deploy:
    machine:
      image: circleci/classic:latest
    steps:
      - attach_workspace:
          at: ~/workspace
      - add_ssh_keys:
          fingerprints:
          - "a7:9e:ca:8a:a9:e1:e8:c8:67:46:d6:b0:76:c7:35:30"
      - run:
          name: "Deploy over SSH"
          command: | 
            export USER_HOST="root@104.131.11.225"
            tar -czf /tmp/build.tar.gz -C ~/workspace/dist .
            
            ssh ${USER_HOST} '
            cd ../; 
            rm -Rf /var/www/intra/source/client/build';'

            scp -r /tmp/build.tar.gz ${USER_HOST}:~/apps/intra/front/build.tar.gz
            ssh ${USER_HOST} '
            cd ~/apps/intra/front;
            tar -xzf ./build.tar.gz;
            cd ~;
            cd ..; 
            rm -rf /var/www/intra/source/client/build;
            cp ~/apps/intra/front/build/ /var/www/intra/source/client/;
workflows:
  version: 2
  ci-dploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
     

